### ISSUE TITLE
define etcd storage layer

### ISSUE THREAD

**Issue by kamilsk** [kamilsk/guard#23]
- executor
- query
- types

**Comment by kamilsk** [comment]
```yaml

  etcd:
    image: guard-etcd:latest
    env_file: ../etcd/.env

  etcd:
    build:
      context:    ../etcd/context
      dockerfile: ../Dockerfile
    ports:
    - ${LOCAL_ETCD_PORT}:2379

```
