### ISSUE TITLE
problem with install command

### ISSUE THREAD

**Issue by kamilsk** [kamilsk/guard#70]
Input:
```yml
account:
  name: QWEPADM
  users:
  - name: gorshkov
```

Expected: account + user + token

Obtained: account

Don't reproduced
```yml
account:
  name: QWEPADM
  users:
  - name: gorshkov
    tokens:
    - expired_at: ~
```
